config/routes.rb
Rails.application.routes.draw do

  root :to => 'public#index'
 
  get 'show/:id', :to => 'public#show', :as => 'public_show'


  resources :employees do
    member do
      get :delete
    end
  end

  resources :departments do
    member do
      get :delete
      end
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/department.rb
class Department < ActiveRecord::Base 
  has_many :employees
end

app/models/employee.rb
class Employee < ActiveRecord::Base 
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  layout 'admin'

  def index
    @departments = Department.all
  end

  def show
    @department = Department.find(params[:id])
  end

  def new
    @department = Department.new
  end

  def create
    #instantiate a new object
    @department = Department.new(department_params)
    #save the object
    if @department.save
      flash[:notice] = "Departmnet created successfully."
      #if save is succesful redirect to the index page
      redirect_to(departments_path)
    else
      #if save fails, redisplay the form
      render('new')
  end
end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    #Find an object
    @department = Department.find(params[:id])
    #update the object
    if @department.update_attributes(department_params)
      flash[:notice] = "Department updated successfully."
      #if save is succesful redirect to the index page
      redirect_to(departments_path(@department))
    else
      #if save fails, redisplay the form
      render('edit')
    end
  end

  def delete
    @department = Department.find(params[:id])
  end

  def destroy
    @department = Department.find(params[:id])
    @department.destroy
    flash[:notice] = "Department destroyed successfully."
    redirect_to(departments_path)

  end


  private

  def department_params
    params.required(:department).permit(:name)
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController


  layout 'admin'
  def index
    @employees = Employee.all
    @departments = Department.all
  end

  def show
    @employee = Employee.find(params[:id])

  end

  def new
    @employee = Employee.new
    @departments = Department.all
  end

  def create
    #instantiate a new object
   @employee = Employee.new(employee_params)
    #save the object
    if @employee.save
      flash[:notice] = "Employee created successfully."

      #if save is succesful redirect to the index page
      redirect_to(employees_path)
    else
      #if save fails, redisplay the form
      render('new')
    end
  end

  def edit
    @employee = Employee.find(params[:id])
    @departments = Department.all

  end

  def update
    #Find an object
    @employee = Employee.find(params[:id])
    #update the object
    if @employee.update_attributes(employee_params)
      flash[:notice] = "Employee updated successfully."

      #if save is succesful redirect to the index page
      redirect_to(employees_path(@employee))
    else
      #if save fails, redisplay the form
      render('edit')
    end
  end

  def delete
    @employee = Employee.find(params[:id])
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    flash[:notice] = "Departmnet deleted successfully."
    redirect_to(employees_path)
  end


  private

  def employee_params
    params.required(:employee).permit(:last_name, :first_name, :job_tittle, :email, :department_id)
  end


end

app/controllers/public_controller.rb
class PublicController < ApplicationController

  layout 'public'

  before_action :setup_navigation


  def index
    #intro text
  end

  def show
    @employee = Employee.where(:department_id => params[:id])
    @department = Department.where(:id => params[:id])
    if @employee.nil?
      redirect_to(root_path)
    else
      #display employee content
    end

  end

  private
  def setup_navigation
    @departments = Department.all
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/departments/delete.html.erb
<%= link_to("<< Back to List", departments_path, :class => 'back-link') %>

<div class="departmnets delete">
  <h2>Delete Department</h2>

  <%= form_for(@department, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this department?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Department") %>
    </div>

  <% end %>
</div>

app/views/departments/edit.html.erb
<%= link_to("<< Back to List", departments_path, :class => 'back-link') %>

<div class="departments new">
  <h2>Create Department</h2>

  <%= form_for(@department) do |f| %>

    <table summary="Department form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Update Department") %>
    </div>

  <% end %>
</div>

app/views/departments/index.html.erb
<div class="department index">
  <h2>Departments</h2>

  <h3><%= link_to("Add New Department", new_department_path, :class => 'action new') %></h3>
  </br>


  <table align="center" class="listing" summary="Department list">
    <tr class="header">
      <th>Id</th>
      <th>Name</th>
      <th>Employees</th>
      <th>Actions</th>
    </tr>
    <% @departments.each do |department| %>
    <tr>
      <td><%= department.id %></td>
      <td><%= department.name %></td>
      <td><%= department.employees.size %></td>
      <td class="actions">
        <%= link_to("Show", department_path(department), :class => 'action show') %>
        <%= link_to("Edit", edit_department_path(department), :class => 'action edit') %>
        <%= link_to("Delete", delete_department_path(department), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/departments/new.html.erb
<%= link_to("<< Back to List", departments_path, :class => 'back-link') %>

<div class="departments new">
  <h2>Create Department</h2>

  <%= form_for(@department) do |f| %>

    <table summary="Department form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Create Department") %>
    </div>

  <% end %>
</div>

app/views/departments/show.html.erb
<%= link_to("<< Back to List", departments_path, :class => 'back-link') %>

<div class="departments show">
  <h2>Show Department</h2>

  <table summary="Department detail view">
    <tr>
      <th>Id</th>
      <td><%= @department.id %></td>
    </tr>
    <tr>
      <th>Name</th>
      <td><%= @department.name %></td>
    </tr>
    <tr>
      <th>Employees</th>
      <td><%= @department.employees.size %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @department.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @department.updated_at %></td>
    </tr>
  </table>

</div>

app/views/employees/_enhanced_form.html.erb

        <li class="ui-field-contain">
            <label >Last Name:</label>
           <%= f.text_field(:last_name) %>
        </li>

        <li class="ui-field-contain">
            <label >First Name:</label>
           <%= f.text_field(:first_name) %>
        </li>

        <li class="ui-field-contain">
            <label >Job Tittle:</label>
           <%= f.text_field(:job_tittle) %>
        </li>
        <li class="ui-field-contain">
            <label >Email:</label>
           <%= f.text_field(:email) %>
        </li>

        <li class="ui-field-contain">
            <label>Department ID:</label>
           <%= f.text_field(:department_id) %>
        </li>

app/views/employees/_form.html.erb
<table summary="Employee form fields">
  <tr>
    <th>Last Name</th>
    <td><%= f.text_field(:last_name) %></td>
  </tr>
  <tr>
    <th>First Name</th>
    <td><%= f.text_field(:first_name) %></td>
  </tr>
  <tr>
    <th>Job Tittle</th>
    <td><%= f.text_field(:job_tittle) %></td>
  </tr>
  <tr>
    <th>Email</th>
    <td><%= f.text_field(:email) %></td>
  </tr>
  <tr>
    <th>Department ID</th>
    <td><%= f.select(:department_id, @departments.map {|d| [d.name, d.id]}) %></td>
  </tr>

</table>

app/views/employees/delete.html.erb
 
<%= link_to("<< Back to List", employees_path, :class => 'back-link') %>

<div class="employees delete">
  <h2>Delete Employee</h2>

  <%= form_for(@employee, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this employee?</p>

    <p class="reference-name"><%= f.object.last_name %> <%= f.object.first_name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Employee") %>
    </div>

  <% end %>
</div>

app/views/employees/edit.html.erb
<%= link_to("<< Back to List", employees_path, :class => 'back-link') %>

<div class="employees new">
  <h2>Create Employee</h2>

  <%= form_for(@employee) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>


    <div class="form-buttons">
      <%= f.submit("Update Employee") %>
    </div>

  <% end %>
</div>

app/views/employees/index.html.erb
<div class="employee index">
  <h2>Employees</h2>

  <h3><%= link_to("Add New Employee", new_employee_path, :class => 'action new') %></h3>
  </br>

  <table align="center" class="listing" summary="Employee list">
    <tr class="header">
      <th>Id</th>
      <th>Last Name</th>
      <th>First Name</th>
      <th>Job Tittle</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
    <% @employees.each do |employee| %>
    <tr>
      <td><%= employee.id %></td>
      <td><%= employee.last_name %></td>
      <td><%= employee.first_name %></td>
      <td><%= employee.job_tittle %></td>
      <td><%= employee.email %></td>
      <td class="actions">
        <%= link_to("Show", employee_path(employee), :class => 'action show') %>
        <%= link_to("Edit", edit_employee_path(employee), :class => 'action edit') %>
        <%= link_to("Delete", delete_employee_path(employee), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/employees/new.html.erb
<%= link_to("<< Back to List", employees_path, :class => 'back-link') %>

<div class="employees new">
  <h2>Create Employee</h2>

  <%= form_for(@employee) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>



    <div class="form-buttons">
      <%= f.submit("Create Employee") %>
    </div>



  <% end %>
</div>

app/views/employees/show.html.erb
<%= link_to("<< Back to List", employees_path, :class => 'back-link') %>

<div class="employees show">
  <h2>Show Employee</h2>

  <table summary="Employee detail view">
    <tr>
      <th>Id</th>
      <td><%= @employee.id %></td>
    </tr>
    <tr>
      <th>Last Name</th>
      <td><%= @employee.last_name %></td>
    </tr>
    <tr>
      <th>First Name</th>
      <td><%= @employee.first_name %></td>
    </tr>
    <tr>
      <th>Job Tittle</th>
      <td><%= @employee.job_tittle %></td>
    </tr>
    <tr>
      <th>Email</th>
      <td><%= @employee.email %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @employee.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @employee.updated_at %></td>
    </tr>
  </table>

</div>

app/views/layouts/_navigation.html.erb

<ul>
  <br/>
<li><%= link_to_unless_current("Home",root_path) %></li>


<br/>
<hr>
<br/>
<li><%= link_to_unless_current("Manage Departments",departments_path) %></li>
<li><%= link_to_unless_current("Manage Employees",employees_path) %></li>

<br/>
<hr>
<li><h2> Departments </h2></li>
  <% departments ||= [] %>
  <ul>

      <% departments.each do |department| %>
        <li><%= link_to_unless_current(department.name, public_show_path(department.id)) %></li>
      <% end %>

  </ul>
</ul>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Management: <%= @page_title || "Admin Area" %></title>
     <%= stylesheet_link_tag('application', :media => 'all') %>
           <!-- Change application to admin to change css files-->

   </head>
  <body>

      <div id="header">
          <h1>Management Area</h1>
      </div>


      <div id="main">

                  <div id="navigation">
                     <%= render(:partial => 'layouts/navigation', :locals => { :departments => @departments} ) %>
                  </div>


          <% if !flash[:notice].blank? %>
          <div class="notice">
            <%= flash[:notice] %>
          </div>
         <% end %>

        <div id="content">
            <%= yield %>
        </div>

      </div>

      <div id="footer">
          <p id="copyright">&copy; jctorres</p>
      </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track': 'reload') %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title>Employee Management Home %></title>
      <%= stylesheet_link_tag('application', :media => 'all') %>
   </head>
  <body>

      <div id="header">
          <h1>Management Area</h1>
      </div>


      <div id="main">

          <div id="navigation">
             <%= render(:partial => 'layouts/navigation', :locals => { :departments => @departments} ) %>
          </div>


          <div id="content">
            <%= yield %>
          </div>

          <div class="clear"></div>

      </div>

      <div id="footer">
          <p id="copyright">&copy; jctorres</p>
      </div>


  </body>
</html>